### ISSUE TITLE
question: relation to terraform-aws-eks-workers?

### ISSUE THREAD

**Issue by shaunc** [cloudposse/terraform-aws-eks-node-group#2]
[Question from EKS newbie]: What is the relationship between node groups and the autoscaling groups created by aws-eks-workers? Are they both Cluster autoscalers, from the point of view of Kubernetes? Is a node group simply an "EKS managed" autoscaling group? I notice that eks-workers has many more parameters....

What are the pros and cons of using each?

**Comment by aknysh** [comment]
@shaunc 
When we created the EKS modules, AWS did not have managed workers for EKS.
That's why we created `terraform-aws-eks-workers`.
Recently AWS introduced managed EKS workers: Node Group.
The module `terraform-aws-eks-node-group` is for that.

Node Group covers everything that we had to create in `workers`, but it's hidden from you, so the node group module is much simpler and generally recommended to use.
Once of the advantages that `eks-workers` has is since you create your own ASG, you can use spot instances - you can't do it in Node Group.

Our EKS modules support all three types of workers, and you can connect all of them to a cluster separately or even all at once:

1. Workers with ASG
https://github.com/cloudposse/terraform-aws-eks-cluster/blob/master/examples/complete/main.tf

2. Node Group
https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/examples/complete/main.tf

3. EKS Fargate profile (and eben Node Group and Fargate profile at the same time)
https://github.com/cloudposse/terraform-aws-eks-fargate-profile/blob/master/examples/complete/main.tf

**Comment by shaunc** [comment]
Thanks! ... so I guess the bottom line is more or less "use eks-workers if you want spot instances, otherwise use node-group"? Slightly annoying on the part of AWS seems to be that the fargate profile selectors require namespace and are immutable. Thus (AFAICT) Fargate profile creation becomes part of application deployment rather than cluster creation (if you are using namespaces for applications). Are there any inefficiencies to having many different Fargate profiles, one per application?

**Comment by aknysh** [comment]
@shaunc 
Yes, agree.
You can create fargate profiles upfront for the namspaces you know you will have.
It's not so simple if you create k8s namespaces dynamically (e.g. each app deployed into its own ns, or unlimitted staging, etc.)
EKS Fargate has so many limitations besides those you mentioned, it is a 'toy' for now.
I would give it another year to mature.
