### ISSUE TITLE
Encrypted EBS For Node Group

### ISSUE THREAD

**Issue by xeon0320** [cloudposse/terraform-aws-eks-node-group#69]
Hi. I'm not sure if this is a bug, or maybe I'm just not understanding it correctly. I'm trying to enable encryption and encrypt the EBS volumes for the Node Groups. 

In my Terraform code, I have added:
`launch_template_disk_encryption_enabled = true
launch_template_disk_encryption_kms_key_id = "ARN of the KMS key"`

After terraform apply, I can see the launch template has the encryption flag set to true and the ARN of the key is also visible. 

But when I go to the ASG, I can see the ASG is actually using a different launch template. 

It seems when I run terraform, the code creates 2 launch templates, and the ASG is not using the one that got updated above. 

Am I missing something here? 

Thanks.

**Comment by Nuru** [comment]
@xeon0320 Thank you for reporting this. I have confirmed that this is a bug that has been present since the disk encryption option was added. 

- In the beginning, this module did not use a launch template. 
- At some point (version 0.8 to 0.11) this module optionally created a launch template if one were needed to use features that were only available via a launch template. The intention was to only create and use a launch template if one were needed (probably so as not to disturb existing clusters), but in order to work around a bug in Terraform, the launch template is always created even if it is not used.
- When the disk encryption flag was added, the setting was added to the launch template, but the flag indicating whether or not to _use_ the launch template was not updated.

This is an easy bug to fix and we will fix it. However, at the moment this module is subject to a code freeze, so it will be a while before the fix is published. 

You can work around this bug by forcing the use of the launch template, which you can do by passing `before_cluster_joining_userdata`. I suggest

```hcl
  before_cluster_joining_userdata = "# Force use of launch template"
```

**Comment by xeon0320** [comment]
@Nuru Thanks for the info. Quick question on the workaround. For the variable `before_cluster_joining_userdata`, what do I need to put in for the value? Do I just need to copy-paste the example you put above, and just use a comment string as the value? Thanks.

**Comment by xeon0320** [comment]
@Nuru I've implemented the workaround above and I have a question. After I deploy the node group using that flag, I see the node group is now using the custom launch template (I'm able to specify encryption and custom AMI ID). Under EKS console -> Compute -> NodeGroups, I can see the custom launch template is listed there. 

But if I go to EC2 -> Auto Scaling Group, and check the newly created ASG, it's still using the default launch template, and not the custom template that's used in EKS node. 

The default and custom launch templates look exactly the same to me, but it's just odd that ASG and Noderoup are using 2 different templates. 

Any input on this issue? Thanks.

**Comment by xeon0320** [comment]
I've played around with this launch template, and here's more info. 

After adding that flag `before_cluster_joining_userdata`, I can confirm my managed node group is using the launch template. It takes my custom AMI ID and I'm able to encrypt the EBS volumes. 

The Auto-Scaling Group (ASG) for that node group for some reason is not using that launch template. It has its own launch template. So now there are two launch template IDs for the same node group. One is attached to the EKS node group, and one is attached to the ASG. If I update my terraform code to use another custom ID, terraform updates the node group's launch template, and somehow the ASG's launch template also gets updated to use the new AMI ID. Terraform plan and apply don't show anything, but I can see the ASG's launch template gets updated. This is still a mystery to me. 

I also edit my terraform code to update tags. I can see terraform plan/apply updates the tags on the node group's launch template, but this time it does not update the tags for the ASG's launch template. 

I guess it's not consistent. If I update the AMI ID, node group's launch template gets updated and automatically it also updates the ASG launch template. Then I see the instances get recycled to match the new AMI ID, so this is expected. 

But I update the just the tags, terraform says it will update the node group's launch template, but after successfully running terraform plan/apply, I see the node group's launch template does not get updated at all (same version). 

I hope this gives you more info. Thanks.
